### ISSUE TITLE
Overide save in model to compress the image will not save the file

### ISSUE THREAD

**Issue by farhan2401** [ehossack/django-backblaze-b2#119]
Hi 
im trying to implement compress to my imagefield. But for some reason it will not upload the image. when I check the image in B2 using ftp. it have 0 bytes. Do you perhaps know why it behave like that? 

Model.py
```
def compress(image):
    temp_name = image.name.split(".")[1]
    im = Image.open(image)
    if im.mode != "RGB":
        im = im.convert("RGB")
    im_io = BytesIO()
    im.save(im_io, "JPEG", optimize=True, quality=50)
    new_image = File(im_io, name=image.name)

    return new_image

class Program(models.Model):
  image = models.ImageField(
          upload_to="program_cover",
          blank=False,
          null=False,
          storage=LoggedInStorage,
)
def save(self, *args, **kwargs):
        new_image = compress(self.image)
        self.image = new_image
        super().save(*args, **kwargs)
```

Thanks

**Comment by ehossack** [comment]
Hmm... I'm not exactly sure, as I'm not familiar with `Image` is that Pillow?
You could try compressing files as a wrapper directly in the way django-storages does?

https://github.com/jschneier/django-storages/blob/master/storages/compress.py#L9

**Comment by farhan2401** [comment]
Thanks for replying. I will check on the repo above.
