### ISSUE TITLE
How do i delete files on b2 ?

### ISSUE THREAD

**Issue by jimmy927** [ehossack/django-backblaze-b2#124]
Starting using this now. 
Current Files:    27,778,197

How do I delete files on b2 when the model is deleted ?
Do I need to do it myself ?

**Comment by ehossack** [comment]
Hey @jimmy927 somehow I completely missed your issue -- did you get it resolved? 
By default, Django isn't doing any cleanup, you'd have to use a library like `django-cleanup`

**Comment by ehossack** [comment]
Resolving for now, seeing as no further discussions.
