### ISSUE TITLE
Configuration quarries

### ISSUE THREAD

**Issue by alexdeathway** [ehossack/django-backblaze-b2#131]
I am trying to understand this package integration and have some question.

1. How static files are handled, does _django-backblaze-b2_ replace the internal handling or something since no configuration like DEFAULT_FILE_STORAGE or STATICFILES_STORAGE is defined.

2. Do we need to define storage in each field? Also, is it running parallel to default storage?
```python

class MyModel(models.Model):
    file_field = models.FileField(
        upload_to="uploads",
        storage=BackblazeB2Storage
    )
 ```

**Comment by ehossack** [comment]
So what this library is, is an implementation of Django's storage API, meaning, you can set the [`DEFAULT_FILE_STORAGE`](https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-DEFAULT_FILE_STORAGE) or you can set it on a per-field basis. 

So really up to you how you want to use it. Myself I use it in parallel to default storage as some files are okay on the filesystem but not all.

**Comment by ehossack** [comment]
Haven't heard back so will consider this resolved.
