### ISSUE TITLE
Authorization token doesn't automatically renew after expiration

### ISSUE THREAD

**Issue by anderoonies** [ehossack/django-backblaze-b2#224]
I'm using a subclass `django-backblaze-b2`, with the following configuration:

```py
BACKBLAZE_CONFIG = {
    "account_info": {"type": "django-cache", "cache": "django-backblaze-b2"},
    "application_key_id": os.getenv("BACKBLAZE_KEY_ID", None),
    "application_key": os.getenv("BACKBLAZE_KEY", None),
    "bucket": "<bucket name>",
}

CACHES = {
    'django-backblaze-b2': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
}
```

I'm also subclassing `BackblazeB2Storage` to add the following:

```py
@deconstructible
class BackblazeB2StorageCDN(BackblazeB2Storage):
    
    def _get_file_url(self, name: str) -> str:
        if getattr(settings, 'BACKBLAZE_URL_CACHE', True):
            b2_url = cache.get(name)

            if not b2_url:
                b2_url = self.get_backblaze_url(name)
                cache.set(name, b2_url, 3600)

        else:
            b2_url = self.get_backblaze_url(name)

        if getattr(settings, 'BACKBLAZE_CDN_URL', None):
            b2_download_url = urlparse(b2_url)
            cdn_url = urlparse(settings.BACKBLAZE_CDN_URL)

            file_path = Path(b2_download_url.path)
            file_path = str(Path(*file_path.parts[3:]))
            cdn_url = cdn_url._replace(path=file_path)
            return cdn_url.geturl()
        else:
            return b2_url

```

After 24 hours, presumably when the B2 `authorizationToken` expires, I start seeing these errors:
`couldn't save the photo: unauthorized for application key with capabilities 'listBuckets,writeBuc...`

When erroring, b2sdk makes a request to `b2_authorize_account`, then errors on a `HEAD` request to upload the file.

Based on that, it seems like this is happening within the authorization loop of `b2sdk`.

Is there any issue with my configuration that is resulting in the new `authorizatoinToken` not saving in the cache?

**Comment by anderoonies** [comment]
Related issue on b2sdk: https://github.com/Backblaze/b2-sdk-python/issues/509

**Comment by ehossack** [comment]
So for starters, I'm looking at your code and I can't see why it might cause issues. (I'm also curious as to why the built-in CDN config does not work for you and you added your own code but that's a separate question :P)

For context, the reason to have a shared thread-safe auth account info was because the b2sdk had concurrency issues with their SqliteAccountInfo and the InMemoryAccount info was also not thread-safe and had issues 😅 .

So it's interesting they'd point to this lib as the issue source. I'll take a look at that issue.

**Comment by ehossack** [comment]
Okay, I've done some digging, and here's some thoughts:

1. If you turn on debug logging, does that help with diagnosis? I've added some logging to the latest release that should help with this (6.0.2)
2. It's possible this library's aggressive clearing is causing your issue. I'm not sure which value is `None`, but that could be it. Here's the logic in the lib: https://github.com/ehossack/django-backblaze-b2/commit/7fe64fca0401ceb932c488eb0562080093f17dcc

**Comment by anderoonies** [comment]
Alright, finally got logs. Here's what I'm seeing around one of these errors. I'm going to include some context for these:
```
NGINX: a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/request: "POST <upload photo endpoint> HTTP/1.1" (this error means that the uploaded file is large and being buffered)
B2: file info cache miss for <filename>
B2: unauthorized for application key with capabilities 'readBuckets,writeFiles,readBucketNotifications,readBucketEncryption,writeBucketEncryption,listAllBucketNames,listBuckets,readFiles,readBucketReplications,writeBucketReplications,shareFiles,deleteFiles,writeBucketNotifications,listFiles', restricted to bucket '<bucketname>' (None)
```
so the only new thing here from expanding logging is`file info cache miss for <filename>`


I looked specifically for the `New auth data set` logs; I deployed on 9-12-24 at 11:19 PDT, which forces new auth data. Since then, here are the logs for that specific log:

```
	
2024-09-13 13:00:01.748	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:39.202	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:39.121	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:39.061	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:39.054	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:39.024	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:36.827	host=nomadb2	New auth data set
	
	
2024-09-12 14:06:34.819	host=nomadb2	New auth data set
	
	
2024-09-12 14:05:42.937	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:42.908	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:42.904	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:42.774	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:42.768	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:40.657	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:38.667	host=nomadb1	New auth data set
	
	
2024-09-12 14:05:15.532	host=nomadb2	New auth data set
	
	
2024-09-12 13:00:01.718	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:09.158	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:09.116	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:09.037	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:09.020	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:08.880	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:06.714	host=nomadb2	New auth data set
	
	
2024-09-12 11:23:04.621	host=nomadb2	New auth data set
	
	
2024-09-12 11:22:03.229	host=nomadb1	New auth data set
	
	
2024-09-12 11:22:03.218	host=nomadb1	New auth data set
	
	
2024-09-12 11:22:03.185	host=nomadb1	New auth data set
	
	
2024-09-12 11:22:03.173	host=nomadb1	New auth data set
	
	
2024-09-12 11:22:03.075	host=nomadb1	New auth data set
	
	
2024-09-12 11:22:00.967	host=nomadb1	New auth data set
	
	
2024-09-12 11:21:58.959	host=nomadb1	New auth data set
	
	
2024-09-12 11:21:28.625	host=nomadb2	New auth data set
```

so it seems like the auth data isn't being rewritten, even when things are erroring.

**Comment by ehossack** [comment]
Okay firstly, sorry for the delay here, I've taken a look a few times at this but never typed up a reply and it's long overdue.

I can't see anything from the logs that really paints a clear picture. Are you able to share logs that include the b2sdk logs?

That would answer questions like:
* Is the sdk making a new auth request each time, and failing to persist?
* Is the auth data being stored empty? Or are all auth values being updated each time?

**Comment by anderoonies** [comment]
Thank you for the reply! 

We've switched to an S3 backend to use with the B2 S3 API, so I don't have anything new to share. All the investigation I did is reported above, I don't have much else to share, I'm sorry. I won't have time to investigate this any further, but I also no longer need any assistance, if you'd like to close the issue.

**Comment by ehossack** [comment]
Okay! Glad you were able to get your project working.
