### ISSUE TITLE
Development Server use local storage

### ISSUE THREAD

**Issue by durantsmedia** [ehossack/django-backblaze-b2#50]
First of all thanks for all the great work on this project.

I am somewhat of a newbie at using Django. I would like to use local storage on my development server and only use b2 when my project is running on the production server.

   fileField = models.FileField(
        upload_to="xxxx-xx",
        storage=BackblazeB2Storage,
        null=True,
        blank=True
    )

**Comment by ehossack** [comment]
Hi! Yes this is how you could accomplish this for example:

Say we have `storages.py` which contains the following:
```python
PublicFileStorage = (
    PublicStorage(
        opts={
            "authorizeOnInit": False,
            "cdnConfig": {"baseUrl": settings.BACKBLAZE_CDN_URL, "includeBucketUrlSegments": True}
            if settings.BACKBLAZE_CDN_URL
            else None,
        }
    )
    if settings.USE_CLOUD_STORAGE
    else FileSystemStorage(location=localPublicStoragePath, base_url=settings.MEDIA_URL + "public")
)
```

We can then define a model as:
```
from .storages import PublicFileStorage

def _getFilepath(mymodel: ModelWithFile, uploadFilename: str) -> str:
	return f"file_{uploadFilename}"

class ModelWithFile(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    spreadsheetFile = FileField(
        verbose_name="spreadsheet",
        upload_to=_getFilepath,
        blank=True,
        storage=PublicFileStorage,
        validators=[FileExtensionValidator(["xlsx", "xls", "numbers", "ods", "csv"])],
    )
```

Just be aware that, like the `_getFilepath` method I have defined here, you'll have to ensure that the django migrations reference the storage, or you might find that generating migrations is constantly causing the field to be detected as changed every time you run `makemigrations`

**Comment by durantsmedia** [comment]
Thank you so much for your reply. I am not sure I know how to prevent "you'll have to ensure that the Django migrations reference the storage". Could you please point me in the right direction?

**Comment by ehossack** [comment]
Oh I missed your comment sorry - basically when you create migrations, you'll want the field definitions to refer to that `PublicFileStorage` and not whatever the if statement evaluates to whenever the migration code was/is run. Hope that helps, and feel free to reopen the issue if you encounter a bug while using the library.
