### ISSUE TITLE
Is it possible to override the file URL when using a CDN?

### ISSUE THREAD

**Issue by foozmeat** [ehossack/django-backblaze-b2#8]
I'd like to use a CDN in front of my B2 bucket but it doesn't appear that its possible currently. Am I interpreting the code correctly?

**Comment by ehossack** [comment]
That's correct.

I actually have the same desire myself but haven't had the time to adjust (for my main deployment traffic load is pretty small so I'm just eating the b2 fees).
My goal is to support this workflow: https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN
Is that similar to you?

I likely won't get to this before February. PRs welcome of course ;)

**Comment by foozmeat** [comment]
We're using Fastly but yes its essentially the same. I think for now I'll subclass `BackblazeB2Storage` and override `url()` to do what we need.

**Comment by ehossack** [comment]
Sounds good. I'll update this issue once I've implemented it. If you find any particulars feel free to share snippets and I can add to the implementation.

**Comment by foozmeat** [comment]
here's what I'm using at the moment

```python
@deconstructible
class BackblazeB2StorageCDN(BackblazeB2Storage):
    
    def _getFileUrl(self, name: str) -> str:
        
        if getattr(settings, 'BACKBLAZE_URL_CACHE', True):
            b2_url = cache.get(name)

            if b2_url:
                logger.debug(f"{self.__class__.__name__} CACHED B2 URL for {name} is {b2_url}")
            else:
                b2_url = self.getBackblazeUrl(name)
                logger.debug(f"{self.__class__.__name__} FETCHED B2 URL for {name} is {b2_url}")
                cache.set(name, b2_url, 3600)

        else:
            b2_url = self.getBackblazeUrl(name)

        if getattr(settings, 'BACKBLAZE_CDN_URL', None):
            b2_download_url = urlparse(b2_url)
            cdn_url = urlparse(settings.BACKBLAZE_CDN_URL)

            # The B2 download URL includes a /file/<bucket name> path prefix that we
            # need to remove. Fetching the S3 URL would be cleaner.

            file_path = Path(b2_download_url.path)
            file_path = str(Path(*file_path.parts[3:]))

            # this urlparse docs say to use this private method /shrug
            cdn_url = cdn_url._replace(path=file_path)

            logger.debug(f"{self.__class__.__name__} CDN URL for {name} is {cdn_url.geturl()}")

            return cdn_url.geturl()

        else:
            return b2_url
```

**Comment by foozmeat** [comment]
we found that without the caching there was a heavy performance penalty loading gallery-style pages that required a lot of calls to `getBackblazeUrl()`

**Comment by ehossack** [comment]
So I'm looking at this now and I'm not quite understanding the performance penalty you're talking about.
Is it waiting on many calls to b2? Or something on your server side?

The implementation for getting the url is based on the authorization request and simply building up the url string, so I can't imagine that is the penalty you speak of.

One thing I can theorize is that your app is making many calls on a gallery page, which in turn requires many threads initializing in-memory backblaze account instances. Using a sqlite3 db might be better in this case to share account state?

**Comment by foozmeat** [comment]
Right, there's a gallery view that needs to build up dozens of B2 URLs and the page load is very slow while those calls are made on every request.  I'd have to go back and re-profile it to tell you exactly what we were seeing but caching the result in Redis so it could be used across multiple servers is working well for us.

**Comment by ehossack** [comment]
I see. I’m not super inclined to add caching to the library based on the high level description, but I’m curious if I’m missing a detail!

More about the use case - are the servers distinct such that a given request might be distributed across multiple workers/handlers, and subsequently a sqlite dB would not solve the issue?

I am thinking that caching here as you’ve done is one possible solution, but the library could also store the entire account info in the cache instead and eliminate SQLite entirely...

**Comment by foozmeat** [comment]
That's right, we've got 2 servers behind a load balancer so the caching only needs to occur once. We also run memcached on each server which would provide very-fast if not redundant caching.

If you take advantage of Django's caching layer then you can leave it up to the implementor to decide where to cache that data. As you can see in my code above I don't specify redis but it's set as the default cache for our app.

**Comment by ehossack** [comment]
Sorry for the delay in responding to this thread. I've been pulled into other work but also wanted to have a good solution.

Version 2.X of the library has a caching implementation which I think is actually an improvement in overall thread safety as well. CDN in-progress.

**Comment by ehossack** [comment]
Okay so in version 2.2.0 you can do the following:

* by default in this version, account info is cached in a django cache with the name of `django-backblaze-b2`. So you can add a cache to your `CACHES` section of your settings file with this name (or use the settings to use a different cache name) and you'll get caching behaviour for filename lookups
* add the `cdnConfig` property to the storage settings, and then your public storage URLs will use this instead of the b2 file api.

**Comment by ehossack** [comment]
Please feel free to file a bug / doc request if this doesn't work or you want clarifications.
